# Generated by Django 4.0.4 on 2022-04-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='createpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField()),
                ('template', models.ImageField(upload_to='')),
                ('text1', models.TextField()),
                ('photoup', models.ImageField(upload_to='')),
                ('photobut', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='createstory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField()),
                ('template', models.ImageField(upload_to='')),
                ('text1', models.TextField()),
                ('photoup', models.ImageField(upload_to='')),
                ('photobut', models.ImageField(upload_to='')),
            ],
        ),
    ]
