# Generated by Django 4.0.4 on 2022-04-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_createpost_createstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpost',
            name='caption',
            field=models.TextField(null=True),
        ),
    ]
